/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.pku.coolyr.struts.action;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import cn.pku.coolyr.Domain.User;
import cn.pku.coolyr.Service.UserService;
import cn.pku.coolyr.struts.form.UserForm;

public class FileUpAction extends Action
{

	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)
	{
		UserForm userForm = (UserForm) form;
		String username = userForm.getName();// 取出用户名字
		String password = userForm.getPassword();// 取出密码
		FormFile formFile = userForm.getPhoto();// 取出图片

		// 通过FormFile 我们可以获取关于上传文件（图片）的各种信息
		String fileName = formFile.getFileName();
		String newFileName = "";

		// 截取最后的后缀名，再拼接上UUID号，形成新的文件名。
		// 该方法截取文件名的最后的后缀名，在拼接上UURD号形成新的文件名。
		// 文件名称：100.png
		// 新文件名称:450259ea-35a1-44a2-8df5-c864367bc07f.png
		// 文件大小：40878
		int beginIndex = fileName.lastIndexOf(".");
		String uuid = (java.util.UUID.randomUUID()).toString();
		newFileName = uuid + fileName.substring(beginIndex, fileName.length());
		int fileSize = formFile.getFileSize();

		System.out.println("uuid：" + uuid);
		System.out.println("文件名称：" + fileName);
		System.out.println("新文件名称:" + newFileName);
		System.out.println("文件大小：" + fileSize);

		InputStream is = null;
		OutputStream os = null;
		try
		{
			// 取出输入流
			is = formFile.getInputStream();

			// 得到输出流--文件
			// 得到file文件夹上传到tomcat服务器后的绝对路径
			String storeFilePath = this.getServlet().getServletContext().getRealPath("file");
			System.out.println("storeFilePath = " + storeFilePath);// 打印路径
			os = new FileOutputStream(storeFilePath + "\\" + newFileName);// 保存到服务器的输出流

			int len = 0;// 每次读取的字节数
			byte[] bytes = new byte[1024];// 缓存
			// 循环处理
			while ((len = is.read(bytes)) > 0)
			{
				os.write(bytes, 0, len);
			}

			// 如果用户上传成功，我们就写入到数据库
			UserService userService = new UserService();
			User user = new User();
			user.setUsername(username);
			user.setPassword(password);
			user.setNewphoto(newFileName);
			user.setOldphoto(fileName);
			if (userService.addUser(user))
			{
				return mapping.findForward("fileok");
				
			}
		}
		catch (FileNotFoundException e)
		{
			e.printStackTrace();

		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
		finally
		{
			try
			{
				is.close();
				os.close();
			}
			catch (IOException e)
			{
				e.printStackTrace();
			}
			formFile.destroy();
		}
		return mapping.findForward("fileerr");
	}
}