/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.pku.coolyr.struts.action;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.pku.coolyr.Domain.User;
import cn.pku.coolyr.Service.UserService;

/**
 * MyEclipse Struts Creation date: 08-13-2015
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class FileDownAction extends Action
{
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)
	{
		// 获取用户名
		String username = request.getParameter("username");
		// 获取User对象
		UserService userService = new UserService();
		User user = userService.getUser(username);
		String oldphoto = user.getOldphoto();

		// 设置ＨＴＴＰ协议相应头，告诉浏览器有文件下载
		response.setContentType("text/html;charset=utf-8");
		// 如果下载的文件有中文名，那么我们需要在action中对下载的名字进行重新URL编码
		String photo = null;
		try
		{
			photo = java.net.URLEncoder.encode(oldphoto, "utf-8");
		}
		catch (UnsupportedEncodingException e1)
		{
			// TODO 自动生成的 catch 块
			e1.printStackTrace();
		}
		response.setHeader("Content-Disposition", "attachment;filename=" + photo);

		// 下载文件
		// 获取要下载的文件的绝对路径 = 文件夹路径 + 文件名
		String folderPath = this.getServlet().getServletContext().getRealPath("file");
		String filePath = folderPath + "\\" + user.getNewphoto();
		// 创建文件的输入和输出流
		FileInputStream fileInputStream = null;
		OutputStream outputStream = null;
		byte[] buffer = new byte[1024];

		int len = 0;

		try
		{
			fileInputStream = new FileInputStream(filePath);
			outputStream = response.getOutputStream();
		

			while ((len = fileInputStream.read(buffer)) > 0)
			{
				outputStream.write(buffer, 0, len);
			}
			outputStream.flush();
	
		}
		catch (Exception e)
		{
			// TODO: handle exception
			e.printStackTrace();
			//return null;
			return mapping.findForward("fileDownErr");
		}
		finally
		{
			try
			{
				outputStream.close();
				fileInputStream.close();
			}
			catch (IOException e)
			{
				// TODO 自动生成的 catch 块
				e.printStackTrace();
				//return null;
				return mapping.findForward("fileDownErr");
			}

		}
		
		return null;
//		return mapping.findForward("fileDownOk");

	}
}
