/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.pku.coolyr.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2015
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="registerForm" parameter="flag" scope="request" validate="true"
 */
public class RegisterAction extends DispatchAction
{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward register(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)
	{
		System.out.println("*****register*****");
		DynaActionForm registerForm = (DynaActionForm) form;// TODO Auto-generated method
	
		String name = registerForm.getString("name");
		String passwd = registerForm.get("passwd").toString();
		String email = registerForm.getString("email");
		
		System.out.println("name=" + name + " passwd=" + passwd + " email=" + email );
		return mapping.findForward("registerOk");
	}
}