/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.pku.coolyr.struts.action;

import java.io.FileOutputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import cn.pku.coolyr.struts.form.UploadMoreForm;

/**
 * MyEclipse Struts Creation date: 12-22-2015
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/uploadMore" name="uploadMoreForm" parameter="flag"
 *                scope="request" validate="true"
 */
public class UploadMoreAction extends Action
{
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)
	{
		UploadMoreForm umForm = (UploadMoreForm) form;
		int count = 0;
		try
		{
			count = umForm.getFileCount(); // 获得上传文件的总数
			for (int i = 0; i < count; i++)
			{
				FormFile file = umForm.getFile(i);
				System.out.println(file.getFileName());
				FileOutputStream fos = new FileOutputStream("d:\\" + file.getFileName()); // 创建输出流
				fos.write(file.getFileData()); // 写入
				fos.flush();// 释放
				fos.close(); // 关闭

			}
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
		return mapping.findForward("fileok");

	}
}