/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.pku.coolyr.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.pku.coolyr.Domain.User;
import cn.pku.coolyr.Service.UserService;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2015
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserListAction extends Action
{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)
	{
		UserService userService = new UserService();
		ArrayList<User> userList = userService.getUserList();
		
		request.setAttribute("userList", userList);
		return mapping.findForward("showUserList");
	
	}
	
	
	
	
	
	
}