/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.pku.coolyr.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

public class UserForm extends ActionForm
{

	private String name;

	private String password;

	private FormFile photo;

	public FormFile getPhoto()
	{
		return photo;
	}

	public void setPhoto(FormFile photo)
	{
		this.photo = photo;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getPassword()
	{
		return password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}
}